### ISSUE TITLE
Hello, the 6.9.1 version said the connection reset by peer(104)

### ISSUE THREAD

**Issue by RoversX** [azalinux/realvnc-server-aarch64-manjaro#6]
The 6.9.1 version said the connection reset by peer(104) and I think it's the software itself's problem. I try it on raspberry 4B 8G Ubuntu and Raid Zero Ubuntu and Mantaro version, all of them said the connection reset by peer(104) Is this problem only with me？

**Comment by azalinux** [comment]
Hello, I have 2 raspberry pi 4 - 8Gb device running 6.9.1 on manjaro and vanilla aarch64 os's.  I've also tested 6.9.1 on Fedora and opensuse on my Pi's and also work fine.  I haven't tried Ubuntu but Manjaro should work fine.  

You should check the status of the realvnc service in Manjaro by doing this in a terminal:   systemctl status  vncserver-x11-serviced 

See what error's appear there and in the log file in /var/log

**Comment by RoversX** [comment]
![_2022-06-11_12-0-34.png](https://pic.iqy.ink/i/2022/06/11/62a4a4bf4302c.png)
![6-11_212-16-37.png](https://pic.iqy.ink/i/2022/06/11/62a4a4bf70b43.png)
Hello, the error said "error while loading shared 
libraries: libbcm_host.so: cannot open shared object file: No such file or directory"
So when I use ubuntu 20.04 arm64 I use this way to solve( no arm64 realvnc at that time): [ubuntu mate community](https://ubuntu-mate.community/t/realvnc-install-on-rpi4-with-ubuntumate-20-04-1-lts/22559/11) . For now, I try to install the version 6.9.1 arm64 on ubuntu and it show the peer(104) error. Today I install manjaro arm64 and it shows the same problem on ubuntu. Could this possibly be related to the network environment or other problems?

**Comment by azalinux** [comment]
Hello,

On manjaro, do this in a terminal so that the required library files are where they should be on the system:

   ln -s /opt/vc/lib/libvcos.so /usr/lib/libvcos.so.0
    ln -s /opt/vc/lib/libvchiq_arm.so /usr/lib/libvchiq_arm.so.0
    ln -s /opt/vc/lib/libbcm_host.so /usr/lib/libbcm_host.so.0

Im not going to try ubuntu yet as that opens up a whole new set of issues so stick to manjaro for the time being so that i can try and replicate it.

I note that you are using kernel 5.18 aarch64 rather than manjaro's linux-rpi kernel - did you install the linux kernel manually or grab a testing image for the raspberry Pi version 22.06 Manjaro?  Current versions of manjaro are still 22.04 with the kernel of linux-rpi 5.15.x

**Comment by RoversX** [comment]
Oh, Thank you and I will try it🥳

**Comment by RoversX** [comment]
Thanks again, I think I have already solved it, according to the [RealVNC Server on UBUNTU 20.10 (ARM64) on Raspberry Pi 4 (8GB) by jorgemtds ](https://forums.raspberrypi.com/viewtopic.php?t=288769) I copy the file in the /usr/lib/aarch64-linux-gnu/ (on ubuntu22.04 raspberry4 8G) and transfer it to the Raxda Zero( another arm64 board)(That's why u find Linux kernel so wired) Finally I replace the file in the usr/lib/ and arm64 VNC finally start working. Thanks!
