### ISSUE TITLE
rpi firmware 20231102 breakage

### ISSUE THREAD

**Issue by br6** [azalinux/realvnc-server-aarch64-manjaro#9]
I just upgraded to the firmware from 2023-11-02 and I think its broken my realvnc install
xfce Manjaro on unstable branch rpi4.

this is an output of the following
ldd /usr/bin/vncserver-x11-core
        linux-vdso.so.1 (0x0000ffffa0104000)
        libbcm_host.so.0 => not found
        libvcos.so.0 => not found
        libvchiq_arm.so.0 => not found
        libdl.so.2 => /usr/lib/libdl.so.2 (0x0000ffff9fa50000)
        librt.so.1 => /usr/lib/librt.so.1 (0x0000ffff9fa30000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000ffff9fa10000)
        libm.so.6 => /usr/lib/libm.so.6 (0x0000ffff9f960000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000ffff9f930000)
        libc.so.6 => /usr/lib/libc.so.6 (0x0000ffff9f770000)
        /lib/ld-linux-aarch64.so.1 => /usr/lib/ld-linux-aarch64.so.1 (0x0000ffffa00cb000)

I think its only after the update to the rpi4 firmware?, I did mess around with mesa and installing from aur, the desktop loads up fine. glxinfo is fine

**Comment by azalinux** [comment]
Hello,
Mesa shouldn't affect this so looking at the ldd trace - the 3 firmware files realvnc needs are showing as "not found":
libbcm_host.so.0 => not found
libvcos.so.0 => not found
libvchiq_arm.so.0 => not found

Realvnc needs these files to be in /usr/lib which are linked from /opt/vc/lib - try this to start with (as root) then reboot the pi and see if that fixes it:

    ln -s /opt/vc/lib/libvcos.so /usr/lib/libvcos.so.0
    ln -s /opt/vc/lib/libvchiq_arm.so /usr/lib/libvchiq_arm.so.0
    ln -s /opt/vc/lib/libbcm_host.so /usr/lib/libbcm_host.so.0

i'll download manjaro xfce then swap pacman to use the unstable branch and see if i can replicate it when i get a chance.

**Comment by azalinux** [comment]
well i downloaded the manjaro xfce arm64 image and then changed pacman to unstable and it has screwed things up big time!   It has removed the 'raspberrypi-userland-aarch64-git ' package completely (and also removed the /opt/vc files and lib.so files aswell!)  So now with the  Unstable (and testing) repos,  you can't even install it doing a pacman -S .   

So unstable repo has replaced the userland package with:

raspberrypi-userland-aarch64-git and raspberrypi-utils are in conflict

however raspberrypi-utils don't have the /opt/vc/lib files in usr/lib so that package is no good for realvnc. 
I then cloned the stable userland package and tried to build it and tried to replace raspberrypi-utils package to see if that would work and it didn't and you get into a dependency loop:

:: raspberrypi-userland-aarch64-git and raspberrypi-utils are in conflict (raspberrypi-firmware). Remove raspberrypi-utils? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing raspberrypi-utils breaks dependency 'raspberrypi-utils' required by rpi4-eeprom (which is apart of raspberrypi-firmware)

So i would wait until they sort out what upstream are going to do with these new packages and how they tie in once it gets into stable.  For the time being, either switch back to stable for the time being or copy the 3 files above manually from a git rpi4 source to get around the problem.

I have the lib files here if needed:   https://github.com/azalinux/realvnc-server-aarch64-opensuse/blob/main/pifirmware_libs.tar.gz

**Comment by br6** [comment]
Excellent, thank you for responding, that workaround with the files in opt/vc/lib worked for now.

**Comment by azalinux** [comment]
just to let you know and to close this off - i have done a point release (v7.8.0-2) which addresses the raspberrypi-userland package removal which has now gone into Stable - this will copy the lib files over during installation using either the binary package of compiling manually with git.

**Comment by br6** [comment]
> just to let you know and to close this off - i have done a point release (v7.8.0-2) which addresses the raspberrypi-userland package removal which has now gone into Stable - this will copy the lib files over during installation using either the binary package of compiling manually with git.

Thanks, do I still need those 3 library files in opt/vc/lib ?
I reinstalled and removed the lib folder but the new point release still needs them

I am on unstable

**Comment by azalinux** [comment]
yes you still need those 3 lib files - the 3 source lib files go in /opt/vc/lib (as this is where they usually go with the old raspberrypi-userland package and they are symbolically linked into /usr/lib.

The point release simply copies the source lib files back to /opt/vc/lib and makes sure that there is still a symlink to /usr/lib

**Comment by br6** [comment]
Hello, is this still needed now? can I get rid of old opt/vc/lib  ?

**Comment by azalinux** [comment]
Heya,

I hadn't tried it in the recent point releases so i decided to download the latest raspberrypi iso from scratch from  manjaro, then update it ; then git cloned this repository and removed the /opt/vc/lib build section and to my shock, it installed and ran fine!

So at some point in the v7 release cycle, realvnc have fixed this lib issue without the need to add them in manually.  

So yes look like you can remove these lib files.  Make sure you have the latest v7.11 installed as thats the one i tested and make sure manjaro is up to date also.  You *may* need uninstall your current realvnc version then re-install from scratch if removing the lib files causes an error.

I'll update the PKGBUILD now on git so that will be updated straight away however i'll wait until the next major point release to fix the binary package to reflect this change.
